---

- name: Create Group
  group:
    name: "{{ sickrage_group }}"
    system: no
    state: present 
  become: true

- name: Create User
  user:
    name: "{{ sickrage_user }}"
    group: "{{ sickrage_group }}"
    state: present
    system: no
    createhome: no
    shell: /bin/false
  become: true

- name: Install Dependencies
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python-cheetah
    - python-setproctitle
  become: true
    
- name: Install PIP Dependencies
  pip:
    name: pyopenssl
    state: latest
  become: true

- name: Create Required Dirs
  file:
    path: "{{ item }}"
    owner: "{{ sickrage_user }}"
    group: "{{ sickrage_group }}"
    recurse: yes
    state: directory
    mode: '0755'
  become: true
  with_items:
    - "{{ sickrage_install_dir }}"
    - "{{ sickrage_config_dir }}"

- name: Clone repo from GitHub
  git:
    repo: "{{ sickrage_repo }}"
    dest: "{{ sickrage_install_dir }}"
    version: master
  become: true

- block:

    - name: Get files from backup_target
      find:
        paths: "{{ sickrage_backup_target }}"
      register: found_files

    - name: Get latest backup file
      set_fact:
        __sickrage_restore_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first  }}"

    - name: Set Fact for restore_file
      set_fact:
        sickrage_restore_file: "{{ __sickrage_restore_file.path }}"

  when:
    - sickrage_restore_from_backups
    
- name: Restore Backup --> Extract archive
  unarchive:
    src: "{{ sickrage_restore_file }}"
    dest: "{{ sickrage_config_dir }}"
    copy: no
    owner: "{{ sickrage_user }}"
    group: "{{ sickrage_group }}"
    mode: '0755'
  become: yes
  when: sickrage_restore_file is defined

- name: Enable port on firewall
  command: "{{ item }}"
  with_items:
    - firewall-cmd --permanent --add-port=8081/tcp  # HTTP port
#    - firewall-cmd --permanent --add-port=9090/tcp  # HTTPS port
    - firewall-cmd --reload
  become: true
  when: sickrage_firewall_enabled

- name: Add service
  template:
    src: sickrage.service.j2
    dest: /etc/systemd/system/sickrage.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name:     Enable service
  service:
    name: sickrage.service
    enabled: yes
    state: started
  become: true
