---
- name: Check if installed
  stat: path=/apps/sickrage
  register: check_installed
  changed_when: not check_installed.stat.exists

- name: CentOS Install
  include: "install.yml"
  when:
    - ansible_distribution == 'CentOS'
    - check_installed.stat.exists == False

- name: Configure Backups
  include: "backups.yml"
  when: sickrage_backups_enabled
  