---
- name: Check if installed
  stat: path=/apps/sickrage
  register: check_installed
  changed_when: not check_installed.stat.exists

- name: CentOS Install
  include: "install.yml"
  when: not check_installed.stat.exists

- name: Configure Backups
  include: "backups.yml"
  when: sickrage_backups_enabled

- name: Update
  git:
    repo: "{{ sickrage_repo }}"
    dest: "{{ sickrage_install_dir }}"
    version: master
    update: yes
  notify:
    - restart sickrage
  when: sickrage_allow_updates
